# Generated by Django 5.2.8 on 2026-03-08 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0018_booking_activity_booking_add_ons"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password_hash", models.CharField(max_length=255)),
                ("token", models.CharField(db_index=True, max_length=100, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_token",
                        to="bookings.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Token",
                "verbose_name_plural": "Customer Tokens",
            },
        ),
    ]
