# Generated by Django 5.1.4 on 2026-05-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0019_customer_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_number",
            field=models.CharField(
                blank=True,
                help_text="Unique booking number (SP-YYYYMMDD-XXXX)",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="partybooking",
            name="booking_number",
            field=models.CharField(
                blank=True,
                help_text="Unique booking number (SPPARTY-YYYYMMDD-XXXX)",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="currency",
            field=models.CharField(default="GBP", max_length=3),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("SUMUP", "SumUp"),
                    ("CASH", "Cash"),
                    ("STRIPE", "Stripe"),
                    ("RAZORPAY", "Razorpay"),
                ],
                max_length=20,
            ),
        ),
    ]
