# Generated by Django 5.1.4 on 2026-05-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0020_alter_booking_booking_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="parking_plates",
            field=models.JSONField(
                blank=True,
                help_text="Car registration plates for pre-booked parking: ['LE21 ABC', ...]",
                null=True,
            ),
        ),
    ]
