# Generated by Django 5.1.4 on 2026-06-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0021_add_parking_plates_to_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="partybooking",
            name="dietary_restrictions",
            field=models.TextField(
                blank=True,
                help_text="Dietary restrictions submitted by customer",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="partybooking",
            name="special_requests",
            field=models.TextField(
                blank=True,
                help_text="Customer special requests entered during booking",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="partybooking",
            name="spectators",
            field=models.IntegerField(
                default=0, help_text="Non-participating spectators"
            ),
        ),
    ]
