# Generated by Django 5.1.4 on 2026-07-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0022_add_special_requests_dietary_spectators_to_partybooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="partybooking",
            name="admin_fee_charged",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Admin fees charged for rescheduling",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="partybooking",
            name="deposit_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Deposit amount required/paid",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="partybooking",
            name="original_date",
            field=models.DateField(
                blank=True, help_text="Original date before reschedule", null=True
            ),
        ),
        migrations.AddField(
            model_name="partybooking",
            name="package_price",
            field=models.DecimalField(
                decimal_places=2,
                default=250.0,
                help_text="Base package price",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="partybooking",
            name="payment_type",
            field=models.CharField(
                choices=[("DEPOSIT", "Deposit (50%)"), ("FULL", "Full Payment (100%)")],
                default="FULL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="partybooking",
            name="reschedule_count",
            field=models.IntegerField(
                default=0, help_text="Number of times this party was rescheduled"
            ),
        ),
        migrations.AlterField(
            model_name="partybooking",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_PAYMENT", "Pending Payment"),
                    ("DEPOSIT_PAID", "Deposit Paid"),
                    ("PARTIALLY_PAID", "Partially Paid"),
                    ("FULLY_PAID", "Fully Paid"),
                    ("CONFIRMED", "Confirmed"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("RESCHEDULED", "Rescheduled"),
                    ("EXPIRED", "Expired"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
