# Generated by Django 5.0.6 on 2026-07-15 10:35

from django.db import migrations


def bump_sequences(apps, schema_editor):
    from django.db import connection
    vendor = connection.vendor
    with connection.cursor() as cursor:
        if vendor == 'postgresql':
            try:
                cursor.execute("ALTER SEQUENCE bookings_booking_id_seq RESTART WITH 9000;")
                cursor.execute("ALTER SEQUENCE bookings_partybooking_id_seq RESTART WITH 9000;")
            except Exception as e:
                print(f"Warning: Failed to alter PostgreSQL sequence: {e}")
        elif vendor == 'sqlite':
            try:
                cursor.execute("UPDATE sqlite_sequence SET seq = 8999 WHERE name = 'bookings_booking';")
                cursor.execute("UPDATE sqlite_sequence SET seq = 8999 WHERE name = 'bookings_partybooking';")
            except Exception as e:
                print(f"Warning: Failed to update sqlite_sequence: {e}")


def reverse_bump(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0023_partybooking_admin_fee_charged_and_more"),
    ]

    operations = [
        migrations.RunPython(bump_sequences, reverse_bump),
    ]
