# Generated by Django 5.0.6 on 2026-08-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0024_set_starting_ids"),
        ("shop", "0003_add_min_hours_before_slot"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["activity"], name="bookings_bo_activit_2a6436_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["type"], name="bookings_bo_type_0de20f_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["type", "activity"], name="bookings_bo_type_2a4adf_idx"
            ),
        ),
    ]
