# Generated by Django 5.0.6 on 2026-09-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0025_add_booking_type_activity_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="charity_config_id_snapshot",
            field=models.IntegerField(
                blank=True,
                help_text="ID of the CharityConfig at the time of booking (for traceability)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="charity_name_snapshot",
            field=models.CharField(
                blank=True,
                help_text="Name of the charity as recorded at the time of booking (historical accuracy)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="charity_selected",
            field=models.BooleanField(
                default=False,
                help_text="Whether the customer designated this booking amount for the configured charity",
            ),
        ),
        migrations.AddField(
            model_name="partybooking",
            name="charity_config_id_snapshot",
            field=models.IntegerField(
                blank=True,
                help_text="ID of the CharityConfig at the time of booking (for traceability)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="partybooking",
            name="charity_name_snapshot",
            field=models.CharField(
                blank=True,
                help_text="Name of the charity as recorded at the time of booking (historical accuracy)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="partybooking",
            name="charity_selected",
            field=models.BooleanField(
                default=False,
                help_text="Whether the customer designated this booking amount for the configured charity",
            ),
        ),
        migrations.AddField(
            model_name="partybookinghistory",
            name="charity_config_id_snapshot",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partybookinghistory",
            name="charity_name_snapshot",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="partybookinghistory",
            name="charity_selected",
            field=models.BooleanField(
                default=False,
                help_text="Whether the customer designated this booking amount for charity",
            ),
        ),
        migrations.AddField(
            model_name="sessionbookinghistory",
            name="charity_config_id_snapshot",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sessionbookinghistory",
            name="charity_name_snapshot",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sessionbookinghistory",
            name="charity_selected",
            field=models.BooleanField(
                default=False,
                help_text="Whether the customer designated this booking amount for charity",
            ),
        ),
    ]
