# Generated by Django 5.1.4 on 2026-07-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0002_alter_emaillog_email_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="reference_id",
            field=models.CharField(
                blank=True,
                help_text="ID of the related object if no ForeignKey exists",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="reference_type",
            field=models.CharField(
                blank=True,
                help_text="Type of the related object (e.g. Voucher, Customer)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("BOOKING_CONFIRMATION", "Booking Confirmation"),
                    ("BOOKING_REMINDER", "Booking Reminder"),
                    ("BOOKING_CANCELLED", "Booking Cancelled"),
                    ("BOOKING_RESCHEDULED", "Booking Rescheduled"),
                    ("PARTY_BOOKING_CONFIRMATION", "Party Booking Confirmation"),
                    ("PARTY_DEPOSIT_PAID", "Party Deposit Paid"),
                    ("PARTY_FULL_PAID", "Party Full Paid"),
                    ("PARTY_BALANCE_DUE", "Party Balance Due"),
                    ("PARTY_REMINDER", "Party Reminder"),
                    ("PARTY_RESCHEDULED", "Party Rescheduled"),
                    ("PARTY_CANCELLED", "Party Cancelled"),
                    ("PARTY_COMPLETED", "Party Completed"),
                    ("PAYMENT_CONFIRMATION", "Payment Confirmation"),
                    ("PAYMENT_RECEIPT", "Payment Receipt"),
                    ("PAYMENT_INVOICE", "Payment Invoice"),
                    ("PAYMENT_FAILED", "Payment Failed"),
                    ("PAYMENT_REFUNDED", "Payment Refunded"),
                    ("BALANCE_PAID", "Balance Paid"),
                    ("WAIVER_CONFIRMATION", "Waiver Confirmation"),
                    ("WAIVER_REMINDER", "Waiver Reminder"),
                    ("WAIVER_SECURE_LINK", "Waiver Secure Link"),
                    ("ADMIN_WAIVER_NOTIFICATION", "Admin: Waiver Notification"),
                    ("VOUCHER_PURCHASED", "Voucher Purchased"),
                    ("VOUCHER_REDEEMED", "Voucher Redeemed"),
                    ("VOUCHER_EXPIRY_REMINDER", "Voucher Expiry Reminder"),
                    ("GIFT_VOUCHER", "Gift Voucher"),
                    ("MEMBERSHIP_PURCHASED", "Membership Purchased"),
                    ("MEMBERSHIP_RENEWAL", "Membership Renewal Reminder"),
                    ("MEMBERSHIP_EXPIRED", "Membership Expired"),
                    ("MEMBERSHIP_CANCELLED", "Membership Cancelled"),
                    ("MEMBERSHIP_UPDATED", "Membership Updated"),
                    ("MEMBERSHIP_WELCOME", "Membership Welcome"),
                    ("ACCOUNT_WELCOME", "Account Welcome"),
                    ("ACCOUNT_PASSWORD_RESET", "Account Password Reset"),
                    ("ACCOUNT_EMAIL_VERIFICATION", "Account Email Verification"),
                    ("ACCOUNT_EMAIL_CHANGED", "Account Email Changed"),
                    ("ACCOUNT_PROFILE_UPDATED", "Account Profile Updated"),
                    ("ACCOUNT_DELETED", "Account Deleted"),
                    ("FREE_ENTRY_CONFIRMATION", "Free Entry Confirmation"),
                    ("ADMIN_FREE_ENTRY", "Admin: Free Entry"),
                    ("ADMIN_CONTACT_MESSAGE", "Admin: Contact Message"),
                    ("CONTACT_CONFIRMATION", "Contact Message Confirmation"),
                    ("ADMIN_NEW_BOOKING", "Admin: New Booking"),
                    ("ADMIN_PARTY_BOOKING", "Admin: Party Booking"),
                    ("ADMIN_MEMBERSHIP_PURCHASE", "Admin: Membership Purchase"),
                    ("ADMIN_LARGE_BOOKING", "Admin: Large Booking"),
                    ("ADMIN_REFUND_REQUEST", "Admin: Refund Request"),
                    ("ADMIN_PAYMENT_FAILURE", "Admin: Payment Failure"),
                    ("ADMIN_SYSTEM_ERROR", "Admin: System Error"),
                    ("MARKETING_CAMPAIGN", "Marketing Campaign"),
                    ("BIRTHDAY_MARKETING", "Birthday Automation"),
                ],
                help_text="Type of email being sent",
                max_length=50,
            ),
        ),
    ]
