# Generated by Django 5.0.6 on 2026-07-20 14:05

from django.db import migrations


def backfill_emails(apps, schema_editor):
    Customer = apps.get_model('bookings', 'Customer')
    Booking = apps.get_model('bookings', 'Booking')
    PartyBooking = apps.get_model('bookings', 'PartyBooking')
    EmailLog = apps.get_model('emails', 'EmailLog')

    # Backfill ACCOUNT_WELCOME for all customers
    for c in Customer.objects.all():
        if not EmailLog.objects.filter(recipient_email=c.email, email_type='ACCOUNT_WELCOME').exists():
            EmailLog.objects.create(
                email_type='ACCOUNT_WELCOME',
                recipient_email=c.email,
                recipient_name=c.name,
                subject='Welcome to SpinPin!',
                status='SENT',
                template_name='emails/welcome.html',
                context_data={}
            )
            
    # Backfill BOOKING_CONFIRMATION for confirmed/completed bookings
    for b in Booking.objects.filter(status__in=['CONFIRMED', 'COMPLETED']):
        if not EmailLog.objects.filter(booking=b, email_type='BOOKING_CONFIRMATION').exists():
            EmailLog.objects.create(
                booking=b,
                email_type='BOOKING_CONFIRMATION',
                recipient_email=b.email,
                recipient_name=b.name,
                subject=f'Booking Confirmation - SP-{b.id}',
                status='SENT',
                template_name='emails/booking_confirmation.html',
                context_data={}
            )

    # Backfill PARTY_BOOKING_CONFIRMATION for confirmed/completed party bookings
    for pb in PartyBooking.objects.filter(status__in=['CONFIRMED', 'COMPLETED']):
        if not EmailLog.objects.filter(party_booking=pb, email_type='PARTY_BOOKING_CONFIRMATION').exists():
            EmailLog.objects.create(
                party_booking=pb,
                email_type='PARTY_BOOKING_CONFIRMATION',
                recipient_email=pb.email,
                recipient_name=pb.name,
                subject=f'Party Booking Confirmation - SPPARTY-{pb.id}',
                status='SENT',
                template_name='emails/party_confirmation.html',
                context_data={}
            )

def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0003_emaillog_reference_id_emaillog_reference_type_and_more"),
        ("bookings", "0024_set_starting_ids"),
    ]

    operations = [
        migrations.RunPython(backfill_emails, reverse_backfill)
    ]

