# Generated by Django 5.2.8 on 2026-01-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0028_alter_attractionvideosection_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_type",
                    models.CharField(
                        choices=[
                            ("SESSION", "Session Booking"),
                            ("PARTY", "Party Booking"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.TextField(blank=True, null=True)),
                ("content", models.TextField(help_text="Main content/description")),
                (
                    "rules_content",
                    models.TextField(
                        blank=True, help_text="Rules and guidelines content", null=True
                    ),
                ),
                (
                    "sessions_info",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of special sessions with details",
                        null=True,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Booking Information",
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="activity_faqs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Activity-specific FAQs as list of {question, answer}",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="location_info",
            field=models.TextField(
                blank=True, help_text="Location information", null=True
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="what_to_expect",
            field=models.TextField(
                blank=True, help_text="What to expect section", null=True
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="why_choose_us",
            field=models.TextField(
                blank=True, help_text="Why choose this activity section", null=True
            ),
        ),
        migrations.AlterField(
            model_name="legaldocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("TERMS", "Terms & Conditions"),
                    ("DETAILED_RULES", "Detailed Rules"),
                    ("WAIVER", "Participant Waiver"),
                    ("PRIVACY", "Privacy Policy"),
                    ("WAIVER_TERMS", "Waiver Terms"),
                    ("YOUR_RIGHTS", "Your Rights"),
                    ("SECURITY", "Security"),
                    ("COOKIES", "Cookies"),
                    ("DISCLAIMER", "Disclaimer"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
