# Generated by Django 5.2.8 on 2026-02-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0029_bookinginformation_activity_activity_faqs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionbookingconfig",
            name="locker_hire_price",
            field=models.DecimalField(
                decimal_places=2,
                default=2.0,
                help_text="Locker hire price per locker",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="sessionbookingconfig",
            name="parking_price",
            field=models.DecimalField(
                decimal_places=2,
                default=3.0,
                help_text="Parking price per car",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="sessionbookingconfig",
            name="shoe_hire_price",
            field=models.DecimalField(
                decimal_places=2,
                default=1.5,
                help_text="Bowling shoe hire price per pair",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="sessionbookingconfig",
            name="skate_hire_price",
            field=models.DecimalField(
                decimal_places=2,
                default=2.95,
                help_text="Skate hire price per pair",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="sessionbookingconfig",
            name="token_pack_20_price",
            field=models.DecimalField(
                decimal_places=2,
                default=5.0,
                help_text="Arcade token pack (20 tokens)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="sessionbookingconfig",
            name="token_pack_50_price",
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                help_text="Arcade token pack (50 tokens)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="partybookingconfig",
            name="participant_description",
            field=models.CharField(
                default="£14.95 per person",
                help_text="Description shown for participants",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="partybookingconfig",
            name="participant_price",
            field=models.DecimalField(
                decimal_places=2,
                default=14.95,
                help_text="Price per participant in GBP",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="sessionbookingconfig",
            name="adult_description",
            field=models.CharField(
                default="£9.95 per person",
                help_text="Price description for adults",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="sessionbookingconfig",
            name="adult_label",
            field=models.CharField(
                default="Adults (7+ Years)",
                help_text="Display label for adults",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="sessionbookingconfig",
            name="adult_price",
            field=models.DecimalField(
                decimal_places=2,
                default=9.95,
                help_text="Price per adult in GBP",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="sessionbookingconfig",
            name="gst_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="VAT percentage (0 for no VAT)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="sessionbookingconfig",
            name="kid_description",
            field=models.CharField(
                default="£9.95 per person",
                help_text="Price description for kids",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="sessionbookingconfig",
            name="kid_label",
            field=models.CharField(
                default="Kids (1-7 Years)",
                help_text="Display label for kids",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="sessionbookingconfig",
            name="kid_price",
            field=models.DecimalField(
                decimal_places=2,
                default=9.95,
                help_text="Price per kid in GBP",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="sessionbookingconfig",
            name="spectator_description",
            field=models.CharField(
                default="£2.95 per person",
                help_text="Price description for spectators",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="sessionbookingconfig",
            name="spectator_label",
            field=models.CharField(
                default="Spectators (Age 4+)",
                help_text="Display label for spectators",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="sessionbookingconfig",
            name="spectator_price",
            field=models.DecimalField(
                decimal_places=2,
                default=2.95,
                help_text="Price per spectator in GBP",
                max_digits=10,
            ),
        ),
    ]
