# Generated by Django 5.2.8 on 2026-02-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0030_session_booking_addon_prices"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimingCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_label",
                    models.CharField(
                        help_text="e.g. 'Monday – Friday' or 'Weekends'", max_length=100
                    ),
                ),
                (
                    "open_time",
                    models.CharField(
                        help_text="Opening time, e.g. '10:00 AM'", max_length=20
                    ),
                ),
                (
                    "close_time",
                    models.CharField(
                        help_text="Closing time, e.g. '9:00 PM'", max_length=20
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Optional note, e.g. 'Last entry 8 PM'",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="Clock",
                        help_text="Lucide icon name, e.g. 'Clock'",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("accent", "Accent"),
                        ],
                        default="primary",
                        help_text="Card accent color",
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Timing Card",
                "verbose_name_plural": "Timing Cards",
                "ordering": ["order"],
            },
        ),
    ]
