# Generated by Django 5.1.4 on 2026-07-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0031_add_timing_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="ticket_id",
            field=models.CharField(
                blank=True,
                help_text="Unique ticket reference for support",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
