# Generated by Django 5.1.4 on 2026-07-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0032_contactmessage_ticket_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerAccountConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header_title",
                    models.CharField(
                        default="Hi, {name}! 👋",
                        help_text="Use {name} as a placeholder for the customer's first name",
                        max_length=255,
                    ),
                ),
                (
                    "cta_title",
                    models.CharField(default="Book Another Session", max_length=255),
                ),
                (
                    "cta_subtitle",
                    models.CharField(
                        default="Skating, bowling — book your next visit",
                        max_length=255,
                    ),
                ),
                ("cta_link", models.CharField(default="/book", max_length=255)),
                (
                    "empty_state_title",
                    models.CharField(default="No bookings yet", max_length=255),
                ),
                (
                    "empty_state_subtitle",
                    models.CharField(
                        default="Book your first session at Spin Pin!", max_length=255
                    ),
                ),
                (
                    "empty_state_button_text",
                    models.CharField(default="Book Now", max_length=100),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer Account Config",
                "verbose_name_plural": "Customer Account Config",
            },
        ),
    ]
