# Generated by Django 5.0.6 on 2026-09-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0033_customeraccountconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharityConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable or disable the charity option in the booking wizard",
                    ),
                ),
                (
                    "charity_name",
                    models.CharField(
                        default="Nepal Charity",
                        help_text="Name of the charity/cause (e.g. 'Nepal Charity', 'Flood Relief India')",
                        max_length=255,
                    ),
                ),
                (
                    "charity_title",
                    models.CharField(
                        default="Support Nepal",
                        help_text="Display title shown in the booking wizard",
                        max_length=255,
                    ),
                ),
                (
                    "charity_description",
                    models.TextField(
                        default="By confirming this booking for charity, the full booking amount will be donated to support Nepal.",
                        help_text="Short description of the charity/cause shown to the customer",
                    ),
                ),
                (
                    "checkbox_text",
                    models.CharField(
                        default="Yes, I confirm this booking amount should go to Nepal Charity",
                        help_text="Text shown next to the charity confirmation checkbox",
                        max_length=512,
                    ),
                ),
                (
                    "info_text",
                    models.TextField(
                        blank=True,
                        help_text="Optional supporting/informational text shown below the description",
                        null=True,
                    ),
                ),
                (
                    "success_text",
                    models.CharField(
                        blank=True,
                        default="Thank you! Your booking amount will go to Nepal Charity.",
                        help_text="Confirmation text shown after the customer selects the charity option",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional charity logo or image URL",
                        null=True,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Charity Configuration",
                "verbose_name_plural": "Charity Configuration",
            },
        ),
    ]
