"""
Django settings for ninja_backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os
from dotenv import load_dotenv
load_dotenv(BASE_DIR / '.env')

def get_env_bool(name, default=False):
    return (os.getenv(name, str(default)) or '').lower().strip() in ['true', '1', 'yes']

def get_env_list(name, default=''):
    val = os.getenv(name, default)
    return [x.strip() for x in val.split(',') if x.strip()]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-dev-key-fallback')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env_bool('DEBUG', False)  # SAFETY: defaults to False; set DEBUG=True in local .env

# VPS/Local/Azure: Allow all hosts or specific Azure domains
ALLOWED_HOSTS = ['*']

# CORS settings for django-cors-headers (belt)
CORS_ALLOW_ALL_ORIGINS = True
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_HEADERS = [
    'accept', 'accept-encoding', 'authorization',
    'content-type', 'dnt', 'origin', 'user-agent',
    'x-csrftoken', 'x-requested-with',
]
CORS_ALLOW_METHODS = ['DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT']

CSRF_TRUSTED_ORIGINS = [
    'https://spinpin-frontend-d7ftbvf8h8cxe9g5.centralus-01.azurewebsites.net',
    'https://spinpin-backend-cfgcejczfpgyabd7.centralus-01.azurewebsites.net',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'corsheaders',
    'django_filters',

    # Local
    'apps.core',
    'apps.bookings',
    'apps.cms',
    'apps.shop',  # Kept: Voucher model is FK-referenced by Booking/PartyBooking
    'apps.invitations',
    'apps.payments',  # Payment system with mock and SumUp gateways
    'apps.emails.apps.EmailsConfig',  # Email system - use full path to ensure signals are registered
    'apps.marketing.apps.MarketingConfig',  # Azure Email Marketing System
]

MIDDLEWARE = [
    'ninja_backend.force_cors.ForceCORSMiddleware',  # Hard-forces CORS on every response
    'corsheaders.middleware.CorsMiddleware',          # django-cors-headers belt+suspenders
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ninja_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ninja_backend.wsgi.application'


# Upload Constraints
# Limit to 500MB as requested
DATA_UPLOAD_MAX_MEMORY_SIZE = 524288000  # 500 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 524288000  # 500 MB


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url

if 'WEBSITE_SITE_NAME' in os.environ:
    # Running on Azure App Service
    # Use persistent /home/data directory so zip deployments don't overwrite DB
    DATA_DIR = BASE_DIR.parent.parent / 'data' if os.environ.get('WEBSITE_SITE_NAME') else BASE_DIR
    if 'WEBSITE_SITE_NAME' in os.environ:
        from pathlib import Path
        DATA_DIR = Path('/home/data')
        # Ensure the directory exists
        import os
        if not os.path.exists(DATA_DIR):
            try:
                os.makedirs(DATA_DIR)
            except Exception:
                pass
else:
    DATA_DIR = BASE_DIR

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL', f"sqlite:///{DATA_DIR / 'db.sqlite3'}"),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Europe/London"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Whitenoise configuration for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'core.User'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'apps.core.authentication.JWTCookieAuthentication',  # Custom cookie-based JWT auth
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Fallback to header-based
        'rest_framework.authentication.SessionAuthentication',
    ),
    # ── Rate Limiting (no extra package needed — built into DRF) ──────────
    # Public endpoints: max 10 requests/minute per IP
    # Authenticated staff: max 200 requests/minute
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/minute',   # 60 req/min for public (booking form, slot availability)
        'user': '300/minute',  # 300 req/min for authenticated admin staff
    },
    # ── Filtering ─────────────────────────────────────────────────────────
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    # ── Pagination (prevents huge unbounded queries) ───────────────────────
    'DEFAULT_PAGINATION_CLASS': None,  # Per-viewset opt-in only
    # PAGE_SIZE intentionally omitted — set per-viewset where needed
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # Short-lived; refresh token handles long sessions
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Spin Pin API',
    'DESCRIPTION': 'API for Spin Pin - Bowling, Roller Skating & Arcade in Leicester',
    'VERSION': '1.0.0',
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5000",
    "http://localhost:9000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5000",
    "http://127.0.0.1:9000",
    "https://spinpin-frontend-d7ftbvf8h8cxe9g5.centralus-01.azurewebsites.net",
    "https://spinpin.co.uk",
    "https://www.spinpin.co.uk"
]
# Extend with any environment-provided origins
CORS_ALLOWED_ORIGINS.extend(get_env_list('FRONTEND_URLS', ''))

CSRF_TRUSTED_ORIGINS = [
    "https://spinpin-frontend-d7ftbvf8h8cxe9g5.centralus-01.azurewebsites.net",
    "https://spinpin-backend-cfgcejczfpgyabd7.centralus-01.azurewebsites.net",
    "https://spinpin.co.uk",
    "https://www.spinpin.co.uk"
]
CSRF_TRUSTED_ORIGINS.extend(get_env_list('CORS_ALLOWED_ORIGINS', ''))

# Add any additional domains from environment
if 'WEBSITE_HOSTNAME' in os.environ:
    CSRF_TRUSTED_ORIGINS.append(f"https://{os.environ['WEBSITE_HOSTNAME']}")

CORS_ALLOW_CREDENTIALS = True

# In production: only CORS_ALLOWED_ORIGINS are permitted
CORS_ALLOW_ALL_ORIGINS = False

# ====================================================
# HTTPS / SSL PROXY SETTINGS
# ====================================================
# Azure App Service terminates SSL at the load balancer and forwards
# traffic to the app over HTTP with X-Forwarded-Proto: https.
# Without this setting, Django builds all absolute URLs with http://
# which causes Mixed Content errors in the browser.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True


# ====================================================
# STORAGE CONFIGURATION (Azure Blob / Local)
# ====================================================

if 'AZURE_STORAGE_CONNECTION_STRING' in os.environ:
    # Use Azure Blob Storage in production
    DEFAULT_FILE_STORAGE = 'storages.backends.azure_storage.AzureStorage'
    AZURE_CONNECTION_STRING = os.environ['AZURE_STORAGE_CONNECTION_STRING']
    AZURE_CONTAINER = os.environ.get('AZURE_STORAGE_CONTAINER', 'media')

# Always use relative MEDIA_URL to force django-storages to return local paths,
# which will then be proxied through the backend server.
MEDIA_URL = '/media/'

if 'WEBSITE_SITE_NAME' in os.environ:
    from pathlib import Path
    MEDIA_ROOT = str(Path('/home/data/media'))
else:
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# ====================================================
# EMAIL CONFIGURATION (SMTP — VPS ready)
# Configure via .env on your VPS
# ====================================================

# Feature flags
EMAIL_ENABLED = get_env_bool('EMAIL_ENABLED', False)
EMAIL_BOOKING_ENABLED = get_env_bool('EMAIL_BOOKING_ENABLED', False)
EMAIL_DEBUG_MODE = get_env_bool('EMAIL_DEBUG_MODE', True)

# Standard Django SMTP backend
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = get_env_bool('EMAIL_USE_TLS', True)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'info@spinpin.co.uk')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Spin Pin sender name
EMAIL_SENDER_NAME = os.getenv('EMAIL_SENDER_NAME', 'Spin Pin Leicester')

# Email retry
EMAIL_MAX_RETRIES = int(os.getenv('EMAIL_MAX_RETRIES', '3'))
EMAIL_RETRY_DELAY_MINUTES = int(os.getenv('EMAIL_RETRY_DELAY_MINUTES', '1'))

# ====================================================
# AZURE COMMUNICATION SERVICES (Email)
# ====================================================
AZURE_COMMUNICATION_CONNECTION_STRING = os.getenv('AZURE_COMMUNICATION_CONNECTION_STRING', '')
AZURE_EMAIL_SENDER_ADDRESS = os.getenv('AZURE_EMAIL_SENDER_ADDRESS', 'info@spinpin.co.uk')
AZURE_EMAIL_SENDER_NAME = os.getenv('AZURE_EMAIL_SENDER_NAME', 'Spin Pin')

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'apps.emails': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}

# ====================================================
# PAYMENT GATEWAY CONFIGURATION
# ====================================================

# Payment Mode: 'mock' (default, pay at venue) or 'sumup' (live online payments)
PAYMENT_MODE = os.getenv('PAYMENT_MODE', 'mock')

# ── SumUp: Roller Skating & Arcade ─────────────────────────────────────
# Account: SpinPin Ltd
# Used for activity: roller-skating, arcade (and any unknown activity)
SUMUP_SKATING_API_KEY      = os.getenv('SUMUP_SKATING_API_KEY', '')
SUMUP_SKATING_MERCHANT_CODE = os.getenv('SUMUP_SKATING_MERCHANT_CODE', '')

# ── SumUp: Ten Pin Bowling ──────────────────────────────────────────────
# Account: Twinkle Town Ltd (Merchant Code: M7EN4CMZ)
# Used for activity: ten-pin-bowling
SUMUP_BOWLING_API_KEY      = os.getenv('SUMUP_BOWLING_API_KEY', '')
SUMUP_BOWLING_MERCHANT_CODE = os.getenv('SUMUP_BOWLING_MERCHANT_CODE', 'M7EN4CMZ')

# Return URL after payment (same for both merchants)
SUMUP_RETURN_URL = os.getenv('SUMUP_RETURN_URL', 'http://localhost:5000/book/success')

# Legacy single-key fallback (kept for backward compatibility)
SUMUP_API_KEY      = os.getenv('SUMUP_API_KEY', SUMUP_SKATING_API_KEY)
SUMUP_MERCHANT_CODE = os.getenv('SUMUP_MERCHANT_CODE', SUMUP_SKATING_MERCHANT_CODE)

# Legacy Razorpay (no longer used — kept for migration safety)
RAZORPAY_KEY_ID    = os.getenv('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET', '')

# Payment Settings
ALLOW_PARTIAL_PAYMENTS = False  # Require full payment
MINIMUM_DEPOSIT_PERCENTAGE = 50  # Not used when ALLOW_PARTIAL_PAYMENTS = False

