# Generated by Django 5.1.4 on 2026-07-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0003_add_email_tracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketingcampaign",
            name="recipient_type",
            field=models.CharField(
                choices=[
                    ("ALL_ADULTS", "All Adult Waiver Participants"),
                    ("ALL_GUARDIANS", "All Guardians (Waiver)"),
                    ("ALL_BOOKING_CUSTOMERS", "All Session Booking Customers"),
                    ("ALL_PARTY_CUSTOMERS", "All Party Booking Customers"),
                    ("CUSTOM_LIST", "Custom Email List"),
                ],
                default="ALL_ADULTS",
                max_length=30,
            ),
        ),
    ]
