# Generated by Django 5.1.4 on 2026-05-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                default="GBP", help_text="Currency code", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("SUMUP", "SumUp"),
                    ("MOCK", "Mock Gateway"),
                    ("RAZORPAY", "Razorpay"),
                ],
                help_text="Payment gateway provider",
                max_length=20,
            ),
        ),
    ]
